### ISSUE TITLE
When I run the analysis.sh in the readme.txt,I had a problem

### ISSUE THREAD

**Issue by PTK0** [idiap/phonvoc#3]
There is an error:
Config.sh:line 13: /idiap/resource/software/initfiles/shrc: No file or directory
Config.sh: line 19: SETSHELL: command is  not found.
Config.sh: line 20: SETSHELL: command is  not found.
Config.sh: line 22: /idiap/group/speech/common/lib/profile.sh: No file or directory

Can u give me some suggestion? Thanks

**Comment by jiangkid** [comment]
See my issue

**Comment by mcernak** [comment]
I also updated phonvoc/INSTALL to make it more clear for newcomers.
